evpos_accueil:
    path:     /
    defaults: { _controller: EVPOSaffectationBundle:Default:index }

evpos_indicateurs:
    path:     /indicateurs
    defaults: { _controller: EVPOSaffectationBundle:Default:indicateurs }

evpos_listeAppli:
    path:   /application
    defaults: { _controller: EVPOSaffectationBundle:Application:listeAppli }

evpos_cherche_appli:
    path: /application_cherche
    defaults: { _controller: EVPOSaffectationBundle:Application:chercheAppli }

evpos_cherche_uo:
    path: /uo_cherche
    defaults: { _controller: EVPOSaffectationBundle:Application:chercheUo }

evpos_cherche_service:
    path: /service_cherche
    defaults: { _controller: EVPOSaffectationBundle:Organigramme:chercheService }

evpos_listeServiceAppli:
    path:   /service_appli
    defaults: { _controller: EVPOSaffectationBundle:Application:listeAppliService }

evpos_ficheAppli:
    path:  /application/{codeAppli}
    defaults: { _controller: EVPOSaffectationBundle:Application:ficheAppli }

evpos_ficheUo:
    path:   /uo/{codeUo}
    defaults: { _controller: EVPOSaffectationBundle:Application:ficheUo }

evpos_listeSecteur:
    path: /secteur
    defaults: { _controller: EVPOSaffectationBundle:Organigramme:listeSecteur }

evpos_chercheUtilisateur:
    path: /cherche_utilisateur
    defaults: { _controller: EVPOSaffectationBundle:Utilisateur:chercheUtilisateur }

evpos_ficheSecteur:
    path: /secteur/{codeSecteur}
    defaults: { _controller: EVPOSaffectationBundle:Organigramme:ficheSecteur }

evpos_listeUtil:
    path:   /utilisateur
    defaults: { _controller: EVPOSaffectationBundle:Utilisateur:listeUtilisateur }

evpos_ficheUtil:
    path:  /utilisateur/{matUtil}
    defaults: { _controller: EVPOSaffectationBundle:Utilisateur:ficheUtilisateur }

evpos_listeService:
    path:   /service
    defaults: { _controller: EVPOSaffectationBundle:Organigramme:listeService }

evpos_ficheService:
    path: /service/{codeService}
    defaults: { _controller: EVPOSaffectationBundle:Organigramme:ficheService }

evpos_listeDirection:
    path: /direction
    defaults: { _controller: EVPOSaffectationBundle:Organigramme:listeDirection }

evpos_cherchePoste:
    path: /cherche_poste
    defaults: { _controller: EVPOSaffectationBundle:Poste:cherchePoste }

evpos_listePoste:
    path: /poste
    defaults: { _controller: EVPOSaffectationBundle:Poste:listePoste }

evpos_fichePoste:
    path: /poste/{hostname}
    defaults: { _controller: EVPOSaffectationBundle:Poste:fichePoste }

evpos_ficheDirection:
    path: /direction/{codeDirection}
    defaults: { _controller: EVPOSaffectationBundle:Organigramme:ficheDirection }

evpos_listeEc:
    path:   /ec
    defaults: { _controller: EVPOSaffectationBundle:Organigramme:listeEc }

evpos_listeCPI:
    path: /liste_cpi
    defaults: { _controller: EVPOSaffectationBundle:Utilisateur:listeCpi }

# Fonctions d'export
evpos_exportAppliNexthink:
    path:  /appli_ntk
    defaults: { _controller: EVPOSaffectationBundle:Export:exportAppliNexthink }

evpos_exportUoNexthink:
    path:  /uo_ntk
    defaults: { _controller: EVPOSaffectationBundle:Export:exportUoNexthink }

evpos_exportService:
    path: /export_service
    defaults: { _controller: EVPOSaffectationBundle:Export:exportXmlService }

evpos_exportServiceUtil:
    path: /export_service_util
    defaults: { _controller: EVPOSaffectationBundle:Export:exportServiceUtilXml }

evpos_exportServiceRiu:
    path: /export_service_riu
    defaults: { _controller: EVPOSaffectationBundle:Export:exportXmlServiceRiu }

evpos_listeAppliUoXml:
    path:   /application_xml
    defaults: { _controller: EVPOSaffectationBundle:Export:listeAppliUoXml }

evpos_listeAppliUoAllXml:
    path:   /application_all_xml
    defaults: { _controller: EVPOSaffectationBundle:Export:listeAppliUoAllXml }

evpos_listeAppliXml:
    path:   /application_xml_only
    defaults: { _controller: EVPOSaffectationBundle:Export:listeAppliXml }

evpos_listeServiceAppliXml:
    path:   /service_appli_xml
    defaults: { _controller: EVPOSaffectationBundle:Export:listeAppliServiceXml }

evpos_listeDirServicePosteUtilXml:
    path:   /direction_service_poste_util.xml
    defaults: { _controller: EVPOSaffectationBundle:Export:exportDirServicePosteUtilXml }

evpos_exportDirServUtilAppliXml:
    path:  /direction_service_util_appli_xml
    defaults: { _controller: EVPOSaffectationBundle:Export:exportServiceUtilAppliXml }

evpos_exportDirServUtilUoXml:
    path:  /direction_service_util_uo_xml
    defaults: { _controller: EVPOSaffectationBundle:Export:exportServiceUtilUoXml }

evpos_exportDirServUtilUoXml_service:
    path:  /direction_service_util_uo_xml/{codeService}
    defaults: { _controller: EVPOSaffectationBundle:Export:exportServiceUtilUoXmlService }

evpos_exportDirServUtilUoXml_util:
    path:  /direction_service_util_uo_xml/util/{matUtil}
    defaults: { _controller: EVPOSaffectationBundle:Export:exportServiceUtilUoXmlUtil }

# Fonctions d'export CSV
evpos_exportDirectionCsv:
    path: /csv/direction
    defaults: { _controller: EVPOSaffectationBundle:Export:exportCsvDirection }

evpos_exportServiceCsv:
    path: /csv/service
    defaults: { _controller: EVPOSaffectationBundle:Export:exportCsvService }

evpos_exportUtilisateurCsv:
    path: /csv/utilisateur
    defaults: { _controller: EVPOSaffectationBundle:Export:exportCsvUtilisateur }

evpos_exportPosteCsv:
    path: /csv/poste
    defaults: { _controller: EVPOSaffectationBundle:Export:exportCsvPoste }

evpos_exportPosteUtilCsv:
    path: /csv/util_poste
    defaults: { _controller: EVPOSaffectationBundle:Export:exportCsvUtilPoste }

evpos_exportCsvUtilImprimante:
    path: /csv/util_imprimante_degim
    defaults: { _controller: EVPOSaffectationBundle:Export:exportCsvUtilImprimante }

evpos_exportCsvUtilImprimanteDegim:
    path: /csv/util_imprimante_degim/{codeService}
    defaults: { _controller: EVPOSaffectationBundle:Export:exportCsvUtilImprimanteDegim }

# Etat d'avancement des services
evpos_serviceAvancement:
    path: /service_avancement
    defaults: { _controller: EVPOSaffectationBundle:Etat:etatAvancementService }

evpos_serviceAvancementXml:
    path: /service_avancement_xml
    defaults: { _controller: EVPOSaffectationBundle:Etat:etatAvancementServiceXml }

# Pages de contrôle

evpos_ctrl_service_inconnu:
    path: /ctrl_service_inconnu
    defaults: { _controller: EVPOSaffectationBundle:Ctrl:listeServiceInconnu }

evpos_ctrl_poste_inconnu:
    path: /ctrl_poste_inconnu
    defaults: { _controller: EVPOSaffectationBundle:Ctrl:listePosteInconnu }

evpos_ctrl_uo_inconnue:
    path: /ctrl_uo_inconnue
    defaults: { _controller: EVPOSaffectationBundle:Ctrl:listeUoInconnue }

evpos_ctrl_corresp_uo:
    path: /ctrl_corresp_uo
    defaults: { _controller: EVPOSaffectationBundle:Ctrl:listeCorrespUo }

evpos_ctrl_util:
    path: /ctrl_util
    defaults: { _controller: EVPOSaffectationBundle:Ctrl:listeUtilisateurInconnu }

evpos_ctrl_absent:
    path: /ctrl_absent
    defaults: { _controller: EVPOSaffectationBundle:Ctrl:listeAbsentService }

# Fonctions de mise à jour
evpos_update_ensemble_service:
    path: /admin/ensemble_service/{codeService}
    defaults: { _controller: EVPOSaffectationBundle:Update:updateAvancement }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
