login:
    pattern:   /login
    defaults:  { _controller: EVPOSUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

evpos_accueil:
    path:     /
    defaults: { _controller: EVPOSaffectationBundle:Default:index }

evpos_indicateurs:
    path:     /indicateurs
    defaults: { _controller: EVPOSaffectationBundle:Default:indicateurs }

evpos_listeAppli:
    path:   /application
    defaults: { _controller: EVPOSaffectationBundle:Application:listeAppli }

evpos_listeServiceAppli:
    path:   /service_appli
    defaults: { _controller: EVPOSaffectationBundle:Application:listeAppliService }
    
evpos_ficheAppli:
    path:  /application/{codeAppli}
    defaults: { _controller: EVPOSaffectationBundle:Application:ficheAppli }

evpos_ficheUo:
    path:   /uo/{codeUo}
    defaults: { _controller: EVPOSaffectationBundle:Application:ficheUo }

evpos_listeUtil:
    path:   /utilisateur
    defaults: { _controller: EVPOSaffectationBundle:Utilisateur:listeUtilisateur }

evpos_ficheUtil:
    path:  /utilisateur/{matUtil}
    defaults: { _controller: EVPOSaffectationBundle:Utilisateur:ficheUtilisateur }

evpos_listeService:
    path:   /service
    defaults: { _controller: EVPOSaffectationBundle:Utilisateur:listeService }

evpos_ficheService:
    path: /service/{codeService}
    defaults: { _controller: EVPOSaffectationBundle:Utilisateur:ficheService }

evpos_listeDirection:
    path: /direction
    defaults: { _controller: EVPOSaffectationBundle:Utilisateur:listeDirection }
    
evpos_listePoste:
    path: /poste
    defaults: { _controller: EVPOSaffectationBundle:Poste:listePoste }
    
evpos_importPoste:
    path: /import_poste
    defaults: { _controller: EVPOSaffectationBundle:Poste:importPoste }
    

evpos_ficheDirection:
    path: /direction/{codeDirection}
    defaults: { _controller: EVPOSaffectationBundle:Utilisateur:ficheDirection }

evpos_listeEc:
    path:   /ec
    defaults: { _controller: EVPOSaffectationBundle:Utilisateur:listeEc }
 
# Fonctions de mise à jour
evpos_updateUtilFromBAZA:
    path: /update_util_from_baza
    defaults: { _controller: EVPOSaffectationBundle:Update:majBazaUtil } 
    
evpos_updateRiu:
    path: /update_riu
    defaults: { _controller: EVPOSaffectationBundle:Update:majRiu } 

evpos_updateDirServFromBAZA:
    path: /update_ds_from_baza
    defaults: { _controller: EVPOSaffectationBundle:Update:majBazaDirServ } 

evpos_updateFromSUAPP:
    path: /update_from_suapp
    defaults: { _controller: EVPOSaffectationBundle:Update:majSUAPP }
    
evpos_updateAccesService:
    path: /update_acces_service_{codeService}
    defaults: { _controller: EVPOSaffectationBundle:Update:updateAccesService }
    
evpos_updateFromShareCan:
    path: /update_sharecan
    defaults: { _controller: EVPOSaffectationBundle:Update:updateShareCan }

# Fonctions d'export
evpos_exportAppliNexthink:
    path:  /appli_ntk
    defaults: { _controller: EVPOSaffectationBundle:Export:exportAppliNexthink }

evpos_exportUoNexthink:
    path:  /uo_ntk
    defaults: { _controller: EVPOSaffectationBundle:Export:exportUoNexthink }

evpos_listeCPI:
    path: /liste_cpi
    defaults: { _controller: EVPOSaffectationBundle:Utilisateur:listeCpi }
    
evpos_exportService:
    path: /export_service
    defaults: { _controller: EVPOSaffectationBundle:Export:exportXmlService }
    
evpos_exportServiceRiu:
    path: /export_service_riu
    defaults: { _controller: EVPOSaffectationBundle:Export:exportXmlServiceRiu }
    
evpos_listeAppliUoXml:
    path:   /application_xml
    defaults: { _controller: EVPOSaffectationBundle:Export:listeAppliXml }

evpos_listeAppliXml:
    path:   /application_xml_only
    defaults: { _controller: EVPOSaffectationBundle:Export:listeAppliXmlOnly }

evpos_listeServiceAppliXml:
    path:   /service_appli_xml
    defaults: { _controller: EVPOSaffectationBundle:Export:listeAppliServiceXml }    

evpos_exportDirServUtilAppliXml:
    path:  /direction_service_util_appli_xml
    defaults: { _controller: EVPOSaffectationBundle:Export:exportServiceUtilAppliXml }
    
