
evpos_accueil:
    path:     /
    defaults: { _controller: EVPOSaffectationBundle:Default:index }

evpos_indicateurs:
    path:     /indicateurs
    defaults: { _controller: EVPOSaffectationBundle:Default:indicateurs }

evpos_listeAppli:
    path:   /application
    defaults: { _controller: EVPOSaffectationBundle:Application:listeAppli }
    
evpos_cherche_appli:
    path: /application_cherche
    defaults: { _controller: EVPOSaffectationBundle:Application:chercheAppli }

evpos_listeServiceAppli:
    path:   /service_appli
    defaults: { _controller: EVPOSaffectationBundle:Application:listeAppliService }
    
evpos_ficheAppli:
    path:  /application/{codeAppli}
    defaults: { _controller: EVPOSaffectationBundle:Application:ficheAppli }

evpos_ficheUo:
    path:   /uo/{codeUo}
    defaults: { _controller: EVPOSaffectationBundle:Application:ficheUo }

evpos_listeUtil:
    path:   /utilisateur
    defaults: { _controller: EVPOSaffectationBundle:Utilisateur:listeUtilisateur }

evpos_ficheUtil:
    path:  /utilisateur/{matUtil}
    defaults: { _controller: EVPOSaffectationBundle:Utilisateur:ficheUtilisateur }

evpos_listeService:
    path:   /service
    defaults: { _controller: EVPOSaffectationBundle:Organigramme:listeService }

evpos_ficheService:
    path: /service/{codeService}
    defaults: { _controller: EVPOSaffectationBundle:Organigramme:ficheService }

evpos_listeDirection:
    path: /direction
    defaults: { _controller: EVPOSaffectationBundle:Organigramme:listeDirection }
    
evpos_listePoste:
    path: /poste
    defaults: { _controller: EVPOSaffectationBundle:Poste:listePoste }

evpos_fichePoste:
    path: /poste/{hostname}
    defaults: { _controller: EVPOSaffectationBundle:Poste:fichePoste }
    
evpos_importPoste:
    path: /import_poste
    defaults: { _controller: EVPOSaffectationBundle:Poste:importPoste }
    

evpos_ficheDirection:
    path: /direction/{codeDirection}
    defaults: { _controller: EVPOSaffectationBundle:Organigramme:ficheDirection }

evpos_listeEc:
    path:   /ec
    defaults: { _controller: EVPOSaffectationBundle:Organigramme:listeEc }
    
evpos_listeCPI:
    path: /liste_cpi
    defaults: { _controller: EVPOSaffectationBundle:Utilisateur:listeCpi }
 
# Fonctions de mise à jour
evpos_updateUtilFromBAZA:
    path: /update_util_from_baza
    defaults: { _controller: EVPOSaffectationBundle:Update:majBazaUtil } 
    
evpos_updateRiu:
    path: /update_riu
    defaults: { _controller: EVPOSaffectationBundle:Update:majRiu } 

evpos_updateDirServFromBAZA:
    path: /update_ds_from_baza
    defaults: { _controller: EVPOSaffectationBundle:Update:majBazaDirServ } 

evpos_updateFromSUAPP:
    path: /update_from_suapp
    defaults: { _controller: EVPOSaffectationBundle:Update:majSUAPP }
    
evpos_updateAccesService:
    path: /update_acces_service_{codeService}
    defaults: { _controller: EVPOSaffectationBundle:Update:updateAccesService }
    
evpos_updateFromShareCan:
    path: /update_sharecan
    defaults: { _controller: EVPOSaffectationBundle:Update:updateShareCan }

# Fonctions d'export
evpos_exportAppliNexthink:
    path:  /appli_ntk
    defaults: { _controller: EVPOSaffectationBundle:Export:exportAppliNexthink }

evpos_exportUoNexthink:
    path:  /uo_ntk
    defaults: { _controller: EVPOSaffectationBundle:Export:exportUoNexthink }

evpos_exportService:
    path: /export_service
    defaults: { _controller: EVPOSaffectationBundle:Export:exportXmlService }

evpos_exportServiceUtil:
    path: /export_service_util
    defaults: { _controller: EVPOSaffectationBundle:Export:exportServiceUtilXml }
    
evpos_exportServiceRiu:
    path: /export_service_riu
    defaults: { _controller: EVPOSaffectationBundle:Export:exportXmlServiceRiu }
    
evpos_listeAppliUoXml:
    path:   /application_xml
    defaults: { _controller: EVPOSaffectationBundle:Export:listeAppliUoXml }

evpos_listeAppliUoAllXml:
    path:   /application_all_xml
    defaults: { _controller: EVPOSaffectationBundle:Export:listeAppliUoAllXml }

evpos_listeAppliXml:
    path:   /application_xml_only
    defaults: { _controller: EVPOSaffectationBundle:Export:listeAppliXml }

evpos_listeServiceAppliXml:
    path:   /service_appli_xml
    defaults: { _controller: EVPOSaffectationBundle:Export:listeAppliServiceXml }  

evpos_listeDirServicePosteUtilXml:
    path:   /direction_service_poste_util.xml
    defaults: { _controller: EVPOSaffectationBundle:Export:exportDirServicePosteUtilXml }

evpos_exportDirServUtilAppliXml:  
    path:  /direction_service_util_appli_xml  
    defaults: { _controller: EVPOSaffectationBundle:Export:exportServiceUtilAppliXml }  

evpos_exportDirServUtilUoXml:  
    path:  /direction_service_util_uo_xml  
    defaults: { _controller: EVPOSaffectationBundle:Export:exportServiceUtilUoXml }

evpos_exportDirServUtilUoXml_service:  
    path:  /direction_service_util_uo_xml/{codeService}
    defaults: { _controller: EVPOSaffectationBundle:Export:exportServiceUtilUoXmlService }
    
evpos_updateAvancement:
    path: /update_avancement
    defaults: { _controller: EVPOSaffectationBundle:Update:updateAvancementUo }
    
evpos_purgeBase:
    path: /purge_base
    defaults: { _controller: EVPOSaffectationBundle:Update:purgeBase }

# Pages de contrôle
evpos_ctrl_poste_inconnu:
    path: /ctrl_poste_inconnu
    defaults: { _controller: EVPOSaffectationBundle:Ctrl:listePosteInconnu }

evpos_ctrl_uo_inconnue:
    path: /ctrl_uo_inconnue
    defaults: { _controller: EVPOSaffectationBundle:Ctrl:listeUoInconnue }
    
evpos_ctrl_corresp_uo:
    path: /ctrl_corresp_uo
    defaults: { _controller: EVPOSaffectationBundle:Ctrl:listeCorrespUo }
