<?php

namespace EVPOS\affectationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccesServiceUoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccesUtilUoRepository extends EntityRepository
{
	public function getAccesUtilUo($util, $uo) {
        $query = $this->createQueryBuilder('a')
            ->select('a')
            ->setParameter('Uo', $uo)
			->setParameter('Utilisateur', $util)
			->leftJoin('a.uoAcces', 'uo')
			->leftJoin('a.utilAcces', 'u')
            ->where('uo = :Uo and u = :Utilisateur')
            ->getQuery()
        ;
        
        return $query->getOneOrNullResult();
    }
}
