<?php

namespace EVPOS\affectationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccesServiceUoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccesServiceUoRepository extends EntityRepository
{
    public function getListeAccesServiceUo() {
        $query = $this->createQueryBuilder('a')
            ->getQuery()
        ;

        return $query->getResult();
    }
}
