<?php

namespace EVPOS\affectationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CtrlPosteInconnuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CtrlPosteInconnuRepository extends EntityRepository {
	public function getUniques() {
        $query = $this->createQueryBuilder('p')
			->select('p.hostname, count(p.id) as nb')
            ->groupBy('p.hostname')
			->orderBy('p.hostname')
            ->getQuery()
        ;

        return $query->getResult();
    }
}
