<?php

namespace EVPOS\affectationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CtrlUtilisateurInconnuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CtrlUtilisateurInconnuRepository extends EntityRepository
{
    public function listeUtil() {
        $liste = $this->createQueryBuilder('e')
            ->orderBy('e.matUtil')
            ->getQuery()
        ;
        
        return $liste->getResult();
    }
}
