<?php

namespace EVPOS\affectationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CtrlUoInconnueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CtrlUoInconnueRepository extends EntityRepository {
	public function getUniques() {
        $query = $this->createQueryBuilder('u')
			->select('u.codeUo, count(u.id) as nb')
            ->groupBy('u.codeUo')
			->orderBy('u.codeUo')
            ->getQuery()
        ;

        return $query->getResult();
    }
}
