<?php

namespace EVPOS\affectationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HistoUoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoUoRepository extends EntityRepository {
  // Retourne l'historique général d'intégration des UO
  public function getHisto($nature, $niveau) {
    $query=$this->createQueryBuilder('h')
    ->select('h.dateMesure dateMesure, h.avancement, h.nbUo')
    ->setParameter('niveau', $niveau)
    ->setParameter('nature', $nature)
    ->where('h.natureAppli = :nature and h.niveau = :niveau')
    ->orderBy('h.dateMesure', 'ASC')
    ->getQuery()
    ;

    $listeDate = [];

    foreach ($query->getResult() as $ligne) {
      $date = date_format($ligne["dateMesure"], "d/m/Y");

      if ! (in_array($date, $listeDate) {
        $etat[$date]['4. En production'] = 0;
        $listeDate[] = $date;
      }
      $etat[$date][$ligne["avancement"]] = $ligne["nbUo"];
    }

    return $etat;
  }
}
