<?php

namespace EVPOS\affectationBundle\Entity;

/**
 * HistoPosteXpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoPosteXpRepository extends \Doctrine\ORM\EntityRepository
{
  // Retourne l'historique du nombre de poste par jour
  public function getHistoPosteXp() {
    $query=$this->createQueryBuilder('h')
    ->select('h.dateMesure dateMesure, avg(h.nbPosteXp) nbPosteXp')
    ->groupBy('h.dateMesure')
    ->orderBy('h.dateMesure')
    ->getQuery()
    ;
    return $query->getResult();
  }
}
