<?php

namespace EVPOS\affectationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
* HistPosteRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class HistoPosteRepository extends EntityRepository {
  // Retourne l'historique du nombre de poste par jour
  public function getHistoPoste() {
    $query=$this->createQueryBuilder('h')
    ->select('h.dateMesure dateMesure, avg(h.nbPosteMoca) nbMoca, avg(h.nbPosteTodo) nbTodo')
    ->groupBy('h.dateMesure')
    ->orderBy('h.dateMesure')
    ->getQuery()
    ;
    return $query->getResult();
  }

  // Retourne l'historique du nombre de poste migré par semaine
  public function getHistoPosteSemaine() {
    $query=$this->createQueryBuilder('h')
    ->select('h.dateMesure dateMesure, avg(h.nbPosteMoca) nbMoca, avg(h.nbPosteTodo) nbTodo')
    ->groupBy('h.dateMesure')
    ->orderBy('h.dateMesure')
    ->getQuery()
    ;
    $resultSemaine = [];

    foreach ($query->getResult() as $ligne) {
      $resultSemaine[date_format($ligne["dateMesure"], "Y-W")] = $ligne["nbMoca"];
    }
    return $resultSemaine;
  }
}
