<?php

namespace EVPOS\affectationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImprimanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImprimanteRepository extends EntityRepository
{
  /**
	 * Retourne l'imprimante correspondant au hostname passé en paramètre
	 */
	public function getImprimante($hostname) {
		$query = $this->createQueryBuilder('i')
            ->setParameter('hostname', $hostname)
            ->where('i.hostname = :hostname')
            ->getQuery()
        ;

        return $query->getOneOrNullResult();
	}
}
