<?php

namespace EVPOS\affectationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
    /**
     * Retourne la liste de tous les services
     */
    public function getServices() {
        $query = $this->createQueryBuilder('s')
            ->orderBy('s.codeService')
            ->where('s.codeService is not null')
            ->getQuery()
        ;

        return $query->getResult();
    }

    /**
     * Récupération d'un service à partir de son code
     */
    public function getService($codeService) {
        $query = $this->createQueryBuilder('s')
            ->setParameter('code', $codeService)
            ->where('s.codeService = :code')
            ->getQuery()
        ;

        return $query->getSingleResult();
    }

    /**
     * Import des données depuis BAZA
     */
    public function importBaza() {
        $requeteBaza = "select code_direction, lib_long_direction, mat_criu from baz_direction";

        return true;
    }
}
