<?php

namespace EVPOS\affectationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SiloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiloRepository extends EntityRepository
{
  /**
  * Récupération d'un silo à partir de son nom
  */
  public function getSilo($nomSilo) {
    $query = $this->createQueryBuilder('silo')
      ->setParameter('nomSilo', $nomSilo)
      ->where('silo.nomSilo = :nomSilo')
      ->getQuery()
    ;

    return $query->getOneOrNullResult();
  }
}
