<?php

namespace EVPOS\affectationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SiloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiloRepository extends EntityRepository
{
  /**
  * Récupération d'un silo à partir de son nom
  */
  public function getSilo($nomSilo) {
    $query = $this->createQueryBuilder('silo')
      ->setParameter('nomSilo', $nomSilo)
      ->where('silo.nomSilo = :nomSilo')
      ->getQuery()
    ;

    return $query->getOneOrNullResult();
  }

  /**
  * Récupération d'un silo à partir de son identifiant
  */
  public function getSiloId($idSilo) {
    $query = $this->createQueryBuilder('silo')
      ->setParameter('idSilo', $idSilo)
      ->where('silo.idSilo = :idSilo')
      ->getQuery()
    ;

    return $query->getOneOrNullResult();
  }

  /**
   * Retourne la liste des silos qui n'existent plus
   */
  public function listeSiloNonExiste() {
    $query = $this->createQueryBuilder('silo')
      ->where('silo.existe = false')
      ->orderBy('silo.nomSilo')
      ->getQuery()
    ;

    return $query->getResult();
  }

  /**
   * Retourne la liste des silos qui n'existent plus
   */
  public function listeSiloExiste() {
    $query = $this->createQueryBuilder('silo')
      ->where('silo.existe = true')
      ->orderBy('silo.nomSilo')
      ->getQuery()
    ;

    return $query->getResult();
  }
}
