CREATE SEQUENCE evpos_poste_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE TABLE evpos_utilisateur (mat_util VARCHAR2(30) NOT NULL, service_util VARCHAR2(5) DEFAULT NULL, nom_util VARCHAR2(255) NOT NULL, PRIMARY KEY(mat_util));
CREATE INDEX IDX_210C76D91025064F ON evpos_utilisateur (service_util);
CREATE TABLE evpos_service (code_service VARCHAR2(5) NOT NULL, code_direction VARCHAR2(255) DEFAULT NULL, lib_service VARCHAR2(255) NOT NULL, PRIMARY KEY(code_service));
CREATE INDEX IDX_30C85D03920FA98B ON evpos_service (code_direction);
CREATE TABLE evpos_riu_service (service_riu VARCHAR2(5) NOT NULL, mat_riu VARCHAR2(30) NOT NULL, PRIMARY KEY(service_riu, mat_riu));
CREATE INDEX IDX_96E842521E344306 ON evpos_riu_service (service_riu);
CREATE INDEX IDX_96E84252E8BC9E3C ON evpos_riu_service (mat_riu);
CREATE TABLE evpos_acces_service_appli (code_service VARCHAR2(5) NOT NULL, code_appli VARCHAR2(10) NOT NULL, date_import TIMESTAMP(0) DEFAULT NULL, source_import VARCHAR2(30) DEFAULT NULL, PRIMARY KEY(code_service, code_appli));
CREATE INDEX IDX_7BA63A84D93ADE4E ON evpos_acces_service_appli (code_service);
CREATE INDEX IDX_7BA63A844CCD8537 ON evpos_acces_service_appli (code_appli);
CREATE TABLE evpos_application (code_appli VARCHAR2(10) NOT NULL, mat_cpi VARCHAR2(30) DEFAULT NULL, nom_appli VARCHAR2(50) DEFAULT NULL, desc_appli VARCHAR2(2000) DEFAULT NULL, dispo_moca NUMBER(1) DEFAULT NULL, nat_appli VARCHAR2(2) DEFAULT NULL, PRIMARY KEY(code_appli));
CREATE INDEX IDX_984BC8AB7A59A22C ON evpos_application (mat_cpi);
CREATE TABLE evpos_acces_util_appli (mat_util VARCHAR2(30) NOT NULL, code_appli VARCHAR2(10) NOT NULL, date_import TIMESTAMP(0) DEFAULT NULL, source_import VARCHAR2(30) DEFAULT NULL, PRIMARY KEY(mat_util, code_appli));
CREATE INDEX IDX_D4C430ED6DF5720 ON evpos_acces_util_appli (mat_util);
CREATE INDEX IDX_D4C430E4CCD8537 ON evpos_acces_util_appli (code_appli);
CREATE TABLE evpos_uo (code_uo VARCHAR2(10) NOT NULL, code_appli VARCHAR2(10) NOT NULL, nom_uo VARCHAR2(50) DEFAULT NULL, mig_moca NUMBER(1) DEFAULT NULL, avancement_moca VARCHAR2(50) DEFAULT NULL, PRIMARY KEY(code_uo));
CREATE INDEX IDX_F3FEEE7F4CCD8537 ON evpos_uo (code_appli);
CREATE TABLE evpos_direction (code_direction VARCHAR2(255) NOT NULL, mat_criu VARCHAR2(30) DEFAULT NULL, lib_direction VARCHAR2(255) DEFAULT NULL, PRIMARY KEY(code_direction));
CREATE INDEX IDX_A369A3ABC34B8B11 ON evpos_direction (mat_criu);
CREATE TABLE evpos_poste (id NUMBER(10) NOT NULL, hostname VARCHAR2(8) NOT NULL, type VARCHAR2(255) NOT NULL, PRIMARY KEY(id));
ALTER TABLE evpos_utilisateur ADD CONSTRAINT FK_210C76D91025064F FOREIGN KEY (service_util) REFERENCES evpos_service (code_service);
ALTER TABLE evpos_service ADD CONSTRAINT FK_30C85D03920FA98B FOREIGN KEY (code_direction) REFERENCES evpos_direction (code_direction);
ALTER TABLE evpos_riu_service ADD CONSTRAINT FK_96E842521E344306 FOREIGN KEY (service_riu) REFERENCES evpos_service (code_service);
ALTER TABLE evpos_riu_service ADD CONSTRAINT FK_96E84252E8BC9E3C FOREIGN KEY (mat_riu) REFERENCES evpos_utilisateur (mat_util);
ALTER TABLE evpos_acces_service_appli ADD CONSTRAINT FK_7BA63A84D93ADE4E FOREIGN KEY (code_service) REFERENCES evpos_service (code_service);
ALTER TABLE evpos_acces_service_appli ADD CONSTRAINT FK_7BA63A844CCD8537 FOREIGN KEY (code_appli) REFERENCES evpos_application (code_appli);
ALTER TABLE evpos_application ADD CONSTRAINT FK_984BC8AB7A59A22C FOREIGN KEY (mat_cpi) REFERENCES evpos_utilisateur (mat_util);
ALTER TABLE evpos_acces_util_appli ADD CONSTRAINT FK_D4C430ED6DF5720 FOREIGN KEY (mat_util) REFERENCES evpos_utilisateur (mat_util);
ALTER TABLE evpos_acces_util_appli ADD CONSTRAINT FK_D4C430E4CCD8537 FOREIGN KEY (code_appli) REFERENCES evpos_application (code_appli);
ALTER TABLE evpos_uo ADD CONSTRAINT FK_F3FEEE7F4CCD8537 FOREIGN KEY (code_appli) REFERENCES evpos_application (code_appli);
ALTER TABLE evpos_direction ADD CONSTRAINT FK_A369A3ABC34B8B11 FOREIGN KEY (mat_criu) REFERENCES evpos_utilisateur (mat_util);
