ALTER TABLE EVPOS_POSTE ADD (code_materiel VARCHAR2(255) NOT NULL);
ALTER TABLE EVPOS_POSTE DROP (ID);
DROP INDEX primary;
ALTER TABLE EVPOS_POSTE ADD PRIMARY KEY (code_materiel);
ALTER TABLE EVPOS_POSTE MODIFY (hostname  VARCHAR2(8) DEFAULT NULL, type  VARCHAR2(255) DEFAULT NULL);
